[tool.poetry]
name = "process_dynamodb_stream_lambda"
version = "0.1.0"
description = ""
authors = ["Eugene"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
boto3 = "^1.26.24"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
